#pragma config(Sensor, S1,     luz,            sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          izquierda,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,          lapiz,         tmotorEV3_Medium, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          derecha,       tmotorEV3_Large, PIDControl, driveRight, encoder)
//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//

void rotarD(int power_motor)
{
	motor[motorA]=(power_motor);//!!el motor izquierdo gira con la intensidad dada por la funcion!!//
	motor[motorD]=-(power_motor);//!!el motor derecho girara en sentido contrario al motor izquierdo.!!//
}

//!!FUNCION AVANZAR SE LE INDICA EL VALOR CON EL QUE EL MOTOR AVANZARA.!!//
void avanzar(int power_motor)
{
	motor[motorA]=power_motor;
	motor[motorD]=power_motor;
}

//!!FUNCION BAJAR_PLUMON LE INDICAMOS AL MOTORB QUE GIRARA 25 GRADOS A UNA POTENCIA DE 15.!!//

void bajar_plumon()
{
	setMotorTarget(motorB,25,15);
	waitUntilMotorStop(motorB);//ADEMAS AGREGAMOS QUE LA FUNCION TERMINE CUANDO SE LLEGUE A LOS 25 GRADOS DEL MOTOR.!!//
}
//!!FUNCION SUBIR_PLUMON LE INDICAMOS AL MOTORB QUE GIRARA EN 116 GRADOS  EN SENTIDO CONTRARIO A UNA POTENCIA DE 15.!!//

void subir_plumon()
{
	setMotorTarget(motorB,-116,15);
	waitUntilMotorStop(motorB); //!!ADEMAS AGREGAMOS QUE LA FUNCION PARE CUANDO SE LLEGUE A LOS -116 GRADOS DEL MOTOR.!!//
}
/*!!FUNCION QUE SE ENCARGAR DE COMPARAR SI EL COLOR DETECTADO POR EL SENSOR DE COLORES ES MAYOR A 2 Y
/*DISTINTO DE 3 QUE VIENE A SER COLOR VERDE LLAME AL A FUNCION AVANZAR CON UN VALOR DE 15*/

void casilla_blanca()
{
	if(SensorValue[luz]>=2 && SensorValue[luz]!=3){
		avanzar(15);
		}
}

int botonPresionado(){
	if(getButtonPress(buttonRight) == 1){
		return 1;
	}
	if(getButtonPress(buttonLeft) == 1){
		return 2;
	}
	if(getButtonPress(buttonEnter) == 1){
		return 3;
	}
	return 0;
	//}while(getButtonPress(buttonAny == 0));
}

void mostrar_pantalla(int nro)
{
	eraseDisplay ();
	switch(nro) {
		case 0:
			displayStringAt(30,120,"MENU GATO",);
			displayStringAt(30,100,"1-Eleccion de color",);
			displayStringAt(30,90,"2-Jugar",);
			displayStringAt(30,80,"3-Escaneo",);
			displayStringAt(30,70,"4-Mostrar Colores",);
			displayStringAt(30,60,"5.Salir",);
			break;
		case 1:
			displayStringAt(2,60,"Eleccion de color",);
			displayStringAt(2,40,"1-Usuario",);
			displayStringAt(2,30,"2-Contrincante",);
			displayStringAt(2,20,"3-Regresar",);
			break;
		case 2:
			break;
	}
}


int pantalla=0;
int opcion=1;
int cont=1;

task main(){

	eraseDisplay();
	botonPresionado();
	mostrar_pantalla(0);
	displayStringAt(45, 9, "Opcion: %d", opcion);
	switch (botonPresionado()){
					case 1:
						if (opcion == 5){
							opcion = 1;
						}
						else{
							opcion++;
						}
						break;
					case 2:
						if (opcion == 1){
							opcion = 5;
						}
						else{
							opcion--;
						}
						break;
					case 3:
					switch (pantalla){
						case 0:
						switch (opcion){
							case 1:
								mostrar_pantalla(1);
								pantalla = 1;
								break;
							case 2:
								mostrar_pantalla (2);
								pantalla = 2;
								break;
							case 3:
								stopAllTasks ();
								break;
							default:
								break;
				}
			}
		}
		while(true)
		{/*CICLO QUE SE EJECUTA SIEMPRE*/

		casilla_blanca();//*LLAMAMOS LA FUNCION CASILLA_BLANCA*//
		if (SensorValue[luz]==1)//*COMPRUEBA EL SENSOR QUE SI DETECTA EL VALOR CORRESPONDIENTE AL NEGRO LLAME LA FUNCION ROTARD Y AVANZAR CON VALOR -25*//
			{
			rotarD(20);
			avanzar(-25);
			}
		else if ((SensorValue[luz]>=5) && (SensorValue[luz]!=1))//*COMPRUEBA SI EL SENSOR DETECTA UN VALOR MAYOR A 5 Y DISTINTO DE 1 LLAME LA FUNCION BAJAR PLUMON*//
			{
				bajar_plumon();
				//*subir_plumon(); aqui llamamos al a funcion subir plumon pero por falta de tiempo no la implementamos*//
			}
		else if(SensorValue[luz]==3)//*SI EL SENSOR DETECTA EL VALOR 3 CORRESPONDIENTE AL VERDE SE LE SUME 1 A LA VARIABLE CONT*//
			{
			cont=cont+1;
			if (cont==2)//* SI EL VALOR DE CONT ES IGUAL A 2 SE LLAMA LA FUNCION AVANZAR CON VALOR DE 15*//
				{
					avanzar(15);
				 displayBigTextLine(8,"TURNO CONTRINCANTE"); //* Y MUESTRA POR PANTALLA QUE ES EL TURNO DEL CONTRINCANTE PARA QUE JUEGE.*//
				 }
			}
		}
	}

